services:
  rabbit:
    image: "rabbitmq:4.0.2-management"
    container_name: rabbit
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "guest"
      RABBITMQ_DEFAULT_PASS: "guest"
    volumes:
      - ../rabbitmq/data:/var/lib/rabbitmq
      - ../rabbitmq/log:/var/log/rabbitmq
    networks:
      - notification_network

networks:
    notification_network:
       external: true
       name: routes_shared_network